### 1. 根据币种获取配置上下文
GET https://{{host}}:{{port}}/api/v1/settings/list

### 2. 应用所有配置
POST https://{{host}}:{{port}}/api/v1/settings/applyAll
Content-Type: application/json

{
  "instId": "",
  "instType": "SWAP",
  "bars": [
    "15m"
  ],
  "targetWeight": 70,
  "calculateSettingsFaceMap": {
    "MACD": {
      "id": null,
      "enable": true,
      "barSettingsMap": {
        "15m": {
          "weights": 80,
          "shortPeriod": 12,
          "longPeriod": 26,
          "signalPeriod": 9,
          "goldenCrossLine": false,
          "lastPeriod": 4,
          "minContinuityCount": 1,
          "maxContinuityCount": 3,
          "macdTrendTypeMap": {
            "NONE": "FLUCTUATE",
            "BURDEN_DOWN": "FLUCTUATE",
            "PLUS_UP": "FLUCTUATE",
            "BURDEN_UP": "UP",
            "PLUS_DOWN": "DOWN"
          }
        }
      },
      "indicatorType": "MACD"
    }
  },
  "placeOrderSettings": {
    "cash": 1,
    "tdMode": "cross",
    "openOrderType": "market",
    "closeOrderType": "market",
    "retraceRate": 0.5,
    "lever": 100,
    "limit": {
      "maxCount": 1,
      "minIntervalTime": 604800000,
      "type": null,
      "sides": [
        "short",
        "long"
      ],
      "coolingOffTime": 0,
      "openIntervalTime": 28800000,
      "maxPrice": null,
      "minPrice": null
    },
    "profit": {
      "profitRate": 0.008,
      "maxProfitRate": 0.01,
      "greedyOco": {
        "enable": true,
        "greedyOcoRate": 0.002,
        "greedyOcoRateTrigger": 0.002,
        "maxTriggerCount": 4
      },
      "minProfitRate": 0.01
    },
    "stopLossRate": -0.3,
    "positionMaxTime": 604800000,
    "supportMaxTime": false,
    "supportStopLoss": false
  }
}