### 1. 获取模拟器配置
GET https://{{host}}:{{port}}/api/v1/emulatorProperties

### 2. 修改模拟器配置
POST https://{{host}}:{{port}}/api/v1/emulatorProperties
Content-Type: application/json

{
  "task": {
    "limit": 100,
    "runScheduledTask": true
  },
  "runScheduledTaskGroup": true
}