### 模拟器任务 ws 连接
WEBSOCKET ws://127.0.0.1:9003/emulatorTask

### 请求订阅数据
{
  "opCode": 1003,
  "msg": "请求订阅数据",
  "data": {
    "uid": "ACD-ASX-123S-AXS",
    "instId": "BTC-USDT-SWAP",
    "bar": "1d",
    "limit": 100,
    "autoPush": true,
    "settingsContext":
  }
}

### 请求推送数据
{
  "opCode": 1004,
  "msg": "请求推送数据",
  "data": {
    "uid": "ACD-ASX-123S-AXS",
    "instId": "BTC-USDT-SWAP"
  }
}