spring:
  profiles:
    # 默认加载本地的配置. 如果需要加载生产环境的配置, 在启动时添加 -Dspring.profiles.active=prod
    active: local
    include: common

# 程序系统相关配置
app:
  # 系统版本
  version: v0.2.1
  # 项目启动是否启动初始化, 主要是为了订阅数据, 创建okx的连接等初始化操作. 默认 false
  init: false
  # 默认开启 模拟交易
  simulated: true
  mail:
    enable: false
  # 是否能自动下单, 默认false
  order:
    enable: false

# 欧易相关配置
okx:
  rateFile: file:config/SWAP_HOT.json
  allCcyFile: file:config/SWAP.json
  simulated: ${app.simulated}
  syncPrivateTrade: true
  simulated-api:
    api-key: '44cad3f1-1deb-4a2c-9ff0-a36857b2bf08'
    secret-key: '8537260ABE502FCD1C7F373D308AEB12'
    pass-phrase: 'ZZt012818..'

# 模拟器相关配置
emulator:
  task:
    # 模拟器测试任务及其下单数据是否持久化. 默认 true
    store-enable: false

# K-Store 存储引擎相关配置
k-store:
  # 是否是客户端. 如果是false, readLocal和serverUrl配置无效
  isClient: true
  # 是否读取本地文件. 默认true. false 表示通过ws读取数据, 并一定要配置serverUrl
  readLocal: true
  store: store/

# 计算设置相关配置
settings:
  # 排列组合设置. 将下列配置进行排列组合, 并执行相应的模拟器测试
  permutations:
    # 是否启用排列组合, 如果不启动, 则使用默认的下单配置
    version: 'v1.0.0'
    enable: true
    inst-ids: [ 'BTC-USDT-SWAP' ]
    targetWeights: [ 70, 80, 90 ]
    inst-type: SWAP
    limit: 1000000
    bars: [ H_1, D_1 ]
    place-order-settings:
      # 开仓下单类型
      openOrderTypes: [ MARKET ]
      # 平仓下单类型
      closeOrderTypes: [ MARKET ]
      # 回撤率
      retraceRates: [ 0.5 ]
      # 杠杆倍数
      levers: [ 1 ]
      # 止盈
      profitRate: [ 0.01, 0.023 ]
      # 止损
      stopLossRates: [ -0.3 ]
    macdSettings:
      goldenCrossLines: [ true, false ]
      maxContinuityCounts: [ 3, 5 ]
      minContinuityCounts: [ 3 ]
      lastPositionCounts: [ 2 ]
    rsiSettings:
      periods: [ 12, 16 ]
      overboughtList: [ 80, 90 ]
      oversoldList: [ 20, 10 ]
    bollSettings:
      periods: [ 12 ]
      diffMinCountList: [ 1, 3 ]
      minDiffRateList: [ 0.03, 0.4 ]
      retraceRateList: [ 20, 30 ]


ip: 127.0.0.1
