k-store:
  storeRoot: /home/data/k-store/
app:
  # 项目启动是否启动初始化, 主要是为了订阅数据, 创建okx的连接等初始化操作. 默认 false
  init: true
  mail:
    enable: true
  # 是否能自动下单, 默认false. 如果是true, 则需要配置okx的api信息
  # 开启该配置时, 需要十分消息. 请务必审查 okx.simulated 配置的值
  order:
    enable: false

okx:
  rateFile: file:config/SWAP_HOT.json
  allCcyFile: file:config/SWAP.json
  simulated: false # 生产环境, 开始真实交易.
  syncPrivateTrade: true
  supportWsChannelList: PUBLIC, PRIVATE, BUSINESS
  simulated-api:
    api-key: '44cad3f1-1deb-4a2c-9ff0-a36857b2bf08'
    secret-key: '8537260ABE502FCD1C7F373D308AEB12'
    pass-phrase: 'ZZt012818..'

logging:
  level:
    root: info

ip: 127.0.0.1


