= {toc-title}
:author: JouZiton
:doctype: 类型
:encoding: utf-8
:lang: 中文
:numbered: 编号
:stem: latexmath
:icons: font
:source-highlighter: coderay
:sectnums:
:sectlinks:
:sectnumlevels: 4
:toc: left
:toc-title: 项目说明
:toclevels: 3

[preface]
== 前言

- https://www.okx.com/docs-v5/zh/#overview[欧易(OKX)官网 API]

目前只能玩: 合约 + 全仓

== 基本环境

.`开发` / `部署` 环境
- JDK 21
- Maven 3.8.1
- MongoDB last

=== 打版本

.基础命令
[source, shell]
----
git tag -a v0.0.1 -m "v0.0.1"
git push origin v0.0.1
----

.使用现有脚本
[source,shell]
----
sh mvnVersion.sh 0.0.1 'v0.0.1'
git push --tags
----

.脚本已实现功能
- 仓库版本升级
- 如果是以数字结尾的版本, 则打版本号, 但需要自己手动 `push` 版本号

=== 打包

==== Spring boot 打包

在项目目录下执行:

[source,shell]
----
mvn clean install -Dmaven.test.skip=true
----

==== Native 打包（TODO 还没实现）

在``app``目录下执行：

[source,shell]
----
mvn native:compile -Pnative
----


=== 数据收集优化

每次同步数据时都是全量的，可以增量同步

.命令:
[source, shell]
----
zip -r k-store.zip k-store/ -x @exclude.txt
----

.exclude.txt文件内容参考:
[source, txt]
----
*/1m/2021-01
*/1m/2021-02
*/1m/2021-03
----


== 项目说明

=== 基本概念

[NOTE]
====
*重点*: 首先基本概念都参考``欧易官方``提供的``API文档``.
====

==== 产品字段说明

- `ccy`: 基础币种``id``, 例如: `BTC`, `USDT` 等等
- `instId`: 基础币种``全称``, 例如: `BTC-USDT`, `BTC-USDT-SWAP` 等等

== 版本说明

=== v1.0.0

== 配置项说明

=== 配置文件说明

.目前项目配置文件有:
- `application.yml`: 主要存放项目相关的配置.
- `application-common.yml`: 主要存放引入框架的必要配置. 例如: `mongo`、``spring``等配置
- `application-prod.yml`: 主要存放项目生产环境下的配置.
主要是为了区分本地测试和生产环境的配置
- `application-local.yml`:【需要手动创建】 默认加载``本地 local``配置.
主要是用于本地测试用的配置文件, 一般这个文件是不能提交了的.
- 其他配置:
. `logback-spring.xml`: 日志配置文件
. `SWAP_HOT.json`: 常用币种配置文件, 后期应该迁移至数据库管理
. 项目中的``application.yml``: 主要配置端口, 应用名

=== `application.yml` 所有配置项说明

[source, yaml]
----
# 配置项目加载的配置文件
spring:
  profiles:
    # 默认加载本地的配置. 如果需要加载生产环境的配置, 在启动时添加 -Dspring.profiles.active=prod
    active: local
    include: common

# 程序系统相关配置
app:
  # 系统版本, 主要是用于计算版本升级后, 会涉及关键配置的修改.
  version: v0.0.4
  # 项目启动是否启动初始化, 主要是为了订阅数据, 创建okx的连接等初始化操作. 默认 true
  init: true
  # 默认开启 模拟交易
  simulated: true
  # 邮箱相关配置
  mail:
    # 是否开启邮箱通知
    enable: false
    # 邮箱通知列表
    receivers:
      - 528382226@qq.com

  # 是否能自动下单, 默认 false
  order:
    enable: false
  platform:
    # 平台 URL
    url: 'http://43.142.108.229:9003/api/v1/settings/{instId}'

# 欧易相关配置
okx:
  # 是否启用模拟环境, 默认 true
  simulated: ${app.simulated}
  # TODO 是否开启 OKX 连接. 默认开启
  enable: true
  # 常见币种的配置文件. 默认: classpath:SWAP_HOT.json
  rateFile: file:config/SWAP_HOT.json
  # 所有币种的配置文件. 默认: classpath:SWAP.json
  allCcyFile: file:config/SWAP.json
  # 需要订阅的WS 频道. 默认 PUBLIC
  supportWsChannelList: PUBLIC, PRIVATE, BUSINESS
  # 是否通过WS订阅数据. 默认 true
  syncPrivateTrade: true
  # 模拟器账号信息配置
  simulated-api:
    api-key: 'xxx'
    secret-key: 'xxx'
    pass-phrase: 'xxx'
  # 正式账号信息配置
  api:
    api-key: 'xxx'
    secret-key: 'xxx'
    pass-phrase: 'xxx'

k-store:
  # 数据存储根目录. 默认: store/
  storeRoot: store/
----


- *注意*: 场景3的消费速度太慢, 建议使用场景2.

操作方法: 从已经存储的数据中拷贝数据到本地文件中, 然后进行数据读取.

.目标信息
- IP 43.142.108.229
- port 9001
- 用户名: root
- 密码: zhouzhitong
- 数据目录: /home/data/k-store

== 其他

=== 其他修改版本号方式（原先方式）

在顶级 POM 文件所在目录

[source,shell]
----
mvn versions:set -DnewVersion=1.1.0 # 设置新版本号
mvn versions:revert                 # 撤销
mvn versions:commit                 # 确认版本号无误后提交
----

=== 测试优化

本地