### 1. 获取默认配置
GET {{host}}:9003/api/v1/tasksGroups/defaultSettings

### 2. 获取任务组合的数量
PATCH {{host}}:19003/api/v1/tasksGroups/totalCount
Content-Type: application/json

{
  "enable": true,
  "bars": [
    "1H",
    "1D"
  ],
  "targetWeights": [
    80
  ],
  "placeOrderSettings": {
    "openOrderTypes": [
      "market"
    ],
    "closeOrderTypes": [
      "market"
    ],
    "retraceRates": [
      0.5
    ],
    "levers": [
      1
    ],
    "limits": {
      "maxCounts": [
        1
      ],
      "minIntervalTimes": [
        604800000
      ],
      "sides": [
        "long",
        "short"
      ],
      "coolingOffTimes": [
        0
      ],
      "openIntervalTimes": [
        86400000
      ],
      "maxPrices": [
        68000
      ],
      "minPrices": [
        48000
      ]
    },
    "profits": {
      "profitRates": [
        0.023
      ],
      "maxProfitRates": [
        0.5
      ],
      "greedyOcos": {
        "greedyOcoRates": [
          0.005
        ],
        "greedyOcoRateTriggers": [
          0.002
        ],
        "maxTriggerCount": [
          4
        ]
      },
      "minProfitRates": [
        0.003
      ]
    },
    "stopLossRates": [
      0,
      -0.2,
      -0.3
    ]
  },
  "macdSettings": {
    "weights": [
      40,
      80
    ],
    "goldenCrossLines": [
      true,
      false
    ],
    "maxContinuityCounts": [
      3,
      4,
      5
    ],
    "minContinuityCounts": [
      3,
      4
    ],
    "lastPositionCounts": [
      2,
      3
    ],
    "type": "MACD"
  },
  "rsiSettings": {
    "weights": [
      40,
      80
    ],
    "periods": [
      12
    ],
    "overboughtList": [
      80
    ],
    "oversoldList": [
      20
    ],
    "type": "RSI"
  },
  "bollSettings": {
    "weights": [
      40,
      80,
      120
    ],
    "periods": [
      12,
      16,
      24
    ],
    "diffMinCountList": [
      0,
      3
    ],
    "minDiffRateList": [
      0.01,
      0.013,
      0.023
    ],
    "retraceRateList": [
      30,
      20,
      25
    ],
    "type": "BOLL"
  }
}

### 3. 创建自动化任务
POST {{host}}:19003/api/v1/tasksGroups/BTC-USDT-SWAP
Content-Type: application/json

{
  "enable": true,
  "bars": [
    "1H",
    "1D"
  ],
  "targetWeights": [
    80
  ],
  "placeOrderSettings": {
    "openOrderTypes": [
      "market"
    ],
    "closeOrderTypes": [
      "market"
    ],
    "retraceRates": [
      0.5
    ],
    "levers": [
      1
    ],
    "limits": {
      "maxCounts": [
        1
      ],
      "minIntervalTimes": [
        604800000
      ],
      "sides": [
        "long",
        "short"
      ],
      "coolingOffTimes": [
        0
      ],
      "openIntervalTimes": [
        86400000
      ],
      "maxPrices": [
        68000
      ],
      "minPrices": [
        48000
      ]
    },
    "profits": {
      "profitRates": [
        0.023
      ],
      "maxProfitRates": [
        0.5
      ],
      "greedyOcos": {
        "greedyOcoRates": [
          0.005
        ],
        "greedyOcoRateTriggers": [
          0.002
        ],
        "maxTriggerCount": [
          4
        ]
      },
      "minProfitRates": [
        0.003
      ]
    },
    "stopLossRates": [
      0,
      -0.2,
      -0.3
    ]
  },
  "macdSettings": {
    "weights": [
      40,
      80
    ],
    "goldenCrossLines": [
      true,
      false
    ],
    "maxContinuityCounts": [
      3,
      4,
      5
    ],
    "minContinuityCounts": [
      3,
      4
    ],
    "lastPositionCounts": [
      2,
      3
    ],
    "type": "MACD"
  },
  "rsiSettings": {
    "weights": [
      0
    ],
    "periods": [
      12
    ],
    "overboughtList": [
      80
    ],
    "oversoldList": [
      20
    ],
    "type": "RSI"
  },
  "bollSettings": {
    "weights": [
      40,
      80,
      120
    ],
    "periods": [
      12,
      16,
      24
    ],
    "diffMinCountList": [
      0,
      3
    ],
    "minDiffRateList": [
      0.01,
      0.013,
      0.023
    ],
    "retraceRateList": [
      30,
      20,
      25
    ],
    "type": "BOLL"
  }
}
